Header = "TOML-Besispiel"                                                                   #[string]   Titel vom Sendungsreiter

#Referenzen
OrderId = "TOML-1337"                                                                       #[string]   Alphanumerische Auftragsnummer
DeliveryId = "TOML-1337-001"                                                                #[string]   Alphanumerische Lieferscheinnummer

#Absenderprofil & Lieferadresse
Shipper = "Standard"                                                                        #[string]   Name des Absenderprofils
Name = "Consignee ABC AG"                                                                   #[string]   Empfängername
ContactName = "Mr. Skywalker"                                                               #[string]   Name der Kontaktperson
ContactPhone = "+4917287502631"                                                             #[string]   Telefonnummer der Kontaktperson
ContactEmail = "orders@not-existing-company.com"                                            #[string]   Email-Adress der Kontaktperson
Street = "Examplestreet 12a"                                                                #[string]   Straße und Hausnummer
CountryCode = "DE"                                                                          #[string]   ISO-Ländercode
PostCode = "10115"                                                                          #[string]   Postleitzahl
City = "Berlin"                                                                             #[string]   Stadt
PrivateAddress = false                                                                      #[boolean]  Ist privatadresse (Ja/Nein) => (true/false)
NeutralName = "Selling Company ABC GmbH"                                                    #[string]   Neutraler Empfängername
NeutralStreet = "Friedrichstraße 1"                                                         #[string]   Neutrale Straße und Hausnummer
NeutralCountryCode = "DE"                                                                   #[string]   Neutraler ISO-Ländercode
NeutralPostCode = "10115"                                                                   #[string]   Neutrale Postleitzahl
NeutralCity = "Berlin"                                                                      #[string]   Neutrale Stadt

#Versandart
Delivery = "FIX"                                                                            #[string]   Versandart (STANDARD/EXPRESS_8/EXPRESS_10/EXPRESS_12/EXPRESS_16/FIX/FIX_8/FIX_10/FIX_12/FIX_16/DIRECT)
DeliveryDate = 2022-04-14T08:32:55.000Z                                                     #[Datetime] Lieferdatum (für unterstützte Formate siehe TOML-Dokumentation)
PickupDate = 2022-04-12T10:45:32.000Z                                                       #[Datetime] Abholdatum (Bei fehlender Angabe: der nächste Werktag)

#Versanddetails
Incoterm = "STANDARD"                                                                       #[string]   Incoterm (EXW/STANDARD/DDP/INVOICE_TO_RECIPIENT/DAP_CLEARED/DAP_UNCLEARED/FOB)
Premium = false                                                                             #[boolean]  Premiumversand (Ja/Nein) => (true/false)
TailLiftTruckPickup = true                                                                  #[boolean]  Abholung mit Ladebordwand (Ja/Nein) => (true/false)
TailLiftTruckDelivery = true                                                                #[boolean]  Auslieferung mit Ladebordwand (Ja/Nein) => (true/false)
DeliveryWithoutPresence = true                                                              #[boolean]  Abstellgenehmigung erteilen (Ja/Nein) => (true/false)
ClimateNeutral = true                                                                       #[boolean]  Klimaneutrale Auslieferung

#Avisierung
PickupAdvice = false                                                                        #[boolean]  Abholavis, Kontaktaufnahme vor der Abholung (Ja/Nein) => (true/false)
DeliveryAdvice = false                                                                      #[boolean]  Lieferavis, vor Auslieferung Kontaktaufnahme beim Kunden (Ja/Nein) => (true/false)
DriverAdvice = false                                                                        #[boolean]  Fahreravis, kurz vor Asulieferung Anruf vom Fahrer beim Kunden (Ja/Nein) => (true/false)

#Services
Export = false                                                                              #[boolean]  Exportanmeldung durch Spedition (Ja/Nein) => (true/false)
Insurance = true                                                                            #[boolean]  Sendung versichern (Ja/Nein) => (true/false)
Value = 1000                                                                                #[integer]  Warenwert für Versicherung
Currency = "EUR"                                                                            #[string]   Währung (EUR/USD)
Coupon = "WELCOME-CARGOBOARD-123"                                                           #[string]   Coupon-Code

#Benutzerobefläche
ExpandReferences = true                                                                     #[boolean]  Referenzen-Bereich aufklappen (Ja/Nein) => (true/false)
ExpandDeliveryData = false                                                                  #[boolean]  Versanddaten-Bereich aufklappen (Ja/Nein) => (true/false)
ExpandDeliveryType = true                                                                   #[boolean]  Versandart-Bereich aufklappen (Ja/Nein) => (true/false)
ExpandDeliveryDetails = false                                                               #[boolean]  Versanddetails-Bereich aufklappen (Ja/Nein) => (true/false)
ExpandAdvices = false                                                                       #[boolean]  Avisierung-Bereich aufklappen (Ja/Nein) => (true/false)
ExpandServices = false                                                                      #[boolean]  Service-Bereich aufklappen (Ja/Nein) => (true/false)
ExpandNotes = false                                                                         #[boolean]  Notizen-Bereich aufklappen (Ja/Nein) => (true/false)

[[Notes]]                                                                                   #           Fügt die nachfolgende Notiz zur Liste hinzu
Text = "Das ist eine Notiz"                                                                 #[string]   Der Text der Notiz
Checked = false                                                                             #[boolean]  Is abgehakt (Ja/Nein) => (true/false)

[[Notes]]                                                                                   #           Fügt eine weitere Notiz zur Liste hinzu
Text = "Das ist eine abhakte Notiz."                 
Checked = true

[[Packages]]                                                                                #           Fügt das nachfolgende Packstück zur Liste hinzu
Quantity = 1                                                                                #[integer]  Anzahl identischer Packstücke mit folgenden Angabe
Type = "EP"                                                                                 #[string]   Art des Packstücks (für weitere Typen-Codes siehe Benutzeroberfläche)
Content = "Accessories and battery"                                                         #[string]   Inhaltsangabe
Length = 120                                                                                #[integer]  Packstücklänge in cm
Width = 80                                                                                  #[integer]  Packstückbreite in cm
Height = 120                                                                                #[integer]  Packstückhöhe in cm
Weight = 250                                                                                #[float]    Packstückgewicht in Kg
Stackable = true                                                                            #[boolean]  Packstück ist Stapelbar (Ja/Nein) => (true/false)
PaletteExchange = true                                                                      #[boolean]  Palettentausch bei Auslieferung (Ja/Nein) => (true/false)
DatabaseKey = 0                                                                             #[integer]  (Nur für JTL relevant) Interne Paketnummer als Datenbankverweis (tVersand.kVersand)

[[Packages.DangerousGoods]]                                                                 #           Fügt ein Gefahrgut zur Liste des Packstück hinzu
UnNo = "2794"                                                                               #[string]   UN-Nummer des Gefahrenguts
SubstanceName = "BATTERIES (ACCUMULATORS), WET, FILLED WITH ALKALIA, electric collectors"   #[string]   Name der Substanz
TechnicalNameForNotOtherwiseSpecifiedSubstances = "Batterien"                               #[string]   
PackageQuantity = 1                                                                         #[integer]  ???
PackageType = "KOMB"                                                                        #[string]   Verpackungstyp
Quantity = 1                                                                                #[integer]  ???
WeightGross = 100                                                                           #[float]    ???
WeightNetOrVolume = 60                                                                      #[float]    ???
WeightNetOrVolumeUnit = "NGW"                                                               #[string]   ???
RiskMain = "8"                                                                              #[string]   ???
PointsTotal = 180                                                                           #[integer]  ???
PointsMultiplier = 3                                                                        #[float]    ???
AdrVersion = "2022"                                                                         #[string]   ADR-Version
PackagingGroup = "II"                                                                       #[string]   ???
IsExemptedQuantity = false                                                                  #[boolean]  Ist freigestellte Menge
IsLimitedQuantity = false                                                                   #[boolean]  Ist limitierte Menge
IsHighConsequences = false                                                                 #[boolean]  ???
TransportCategory = "2"                                                                     #[string]   ???
TunnelRestrictions = "E"                                                                    #[stirng]   ???

[[Packages]]                                                                                #           Fügt ein weiteres Packstück zur Liste hinzu
Quantity = 2                            
Type = "KT"
Content = "Gefährliche Bananen"
Length = 90
Width = 15
Height = 25
Weight = 32.1
Stackable = false
PaletteExchange = false
DatabaseKey = 1215